language: node_js
node_js:
  - "node"

script:
  - yarn run jest
  - yarn run jest -- --coverage
  
# Send coverage data to Coveralls
after_script: "node ./node_modules/coveralls/bin/coveralls.js -v < ./coverage/lcov.info"
