language: node_js
node_js:
  - "node"

script:
  - yarn run jest
  - yarn run jest --coverage
  
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
